nnstreamer/deviceMLOps.MLAgent

daemon/common.h
daemon/dbus-interface.h
daemon/gdbus-util.c
daemon/gdbus-util.h
daemon/include/meson.build
daemon/include/ml-agent-interface.h
daemon/log.h
daemon/main.c
daemon/meson.build
daemon/ml-agent-interface.c
daemon/ml-agent.pc.in
daemon/model-dbus-impl.cc
daemon/modules.c
daemon/modules.h
daemon/pipeline-dbus-impl.cc
daemon/pkg-mgr.cc
daemon/pkg-mgr.h
daemon/resource-dbus-impl.cc
daemon/service-db.cc
daemon/service-db.hh
dbus/machine-learning-agent.conf.in
dbus/machine-learning-agent.service.in
dbus/meson.build
dbus/model-dbus.xml
dbus/org.tizen.machinelearning.service.service.in
dbus/pipeline-dbus.xml
dbus/resource-dbus.xml
meson.build
meson_options.txt

Initial commit, migrate ml-agent and dbus code from api repo. 
Prepare meson build for dbus and ml-agent first.
TODO:
1. fix version of ml-agent packages.
2. enable testcase.
3. add .spec for tizen release.

[Build] prepare meson build

---

LICENSE
daemon/common.h
daemon/dbus-interface.h
daemon/gdbus-util.c
daemon/gdbus-util.h
daemon/include/ml-agent-interface.h
daemon/log.h
daemon/main.c
daemon/ml-agent-interface.c
daemon/ml-agent.pc.in
daemon/model-dbus-impl.cc
daemon/modules.c
daemon/modules.h
daemon/pipeline-dbus-impl.cc
daemon/pkg-mgr.cc
daemon/pkg-mgr.h
daemon/resource-dbus-impl.cc
daemon/service-db.cc
daemon/service-db.hh
dbus/machine-learning-agent.conf.in

Fix link to main page and update documents.

[Doc] update description

---

daemon/meson.build
meson.build
meson_options.txt
tests/daemon/meson.build
tests/daemon/unittest_gdbus_util.cc
tests/daemon/unittest_ml_agent.cc
tests/daemon/unittest_service_db.cc
tests/dbus/meson.build
tests/dbus/test-dbus-impl.c
tests/dbus/test-dbus-interface.h
tests/dbus/test-dbus.xml
tests/meson.build
tests/services/meson.build
tests/services/org.tizen.machinelearning.service.service.in

Update meson script, add testcases from api repo.

[Build] add testcase

---

.github/CODEOWNERS

Add code reviewers for this repogitory.

[Doc] set reviewers

---

meson.build
packaging/machine-learning-agent.manifest
packaging/machine-learning-agent.spec
packaging/run-unittest.sh
packaging/run_unittests.sh

Fix version and add spec for tizen build.

[Build] add spec for tizen build

---

daemon/service-db.cc

Add condition to check model is registered in database.

[ServiceDB] check model in database

---

daemon/gdbus-util.c
daemon/log.h
daemon/main.c
daemon/model-dbus-impl.cc
daemon/modules.c
daemon/pipeline-dbus-impl.cc
daemon/resource-dbus-impl.cc
daemon/service-db.cc
tests/daemon/unittest_gdbus_util.cc
tests/daemon/unittest_ml_agent.cc
tests/daemon/unittest_service_db.cc
tests/dbus/test-dbus-impl.c

Code clean, rename macro and use predefined log util.

[Log] rename log util

---

daemon/pkg-mgr.cc
tests/daemon/meson.build

Code clean, fix log function and remove unnecessary path in meson.

[CodeClean] build error after enabling tizen

---

daemon/meson.build
daemon/service-db.cc
tests/daemon/unittest_service_db.cc

revise service-db testcases, function to check error case.

[Test] revise service-db test

---

daemon/main.c
daemon/meson.build
daemon/model-dbus-impl.cc
daemon/pipeline-dbus-impl.cc
daemon/pkg-mgr.cc
daemon/resource-dbus-impl.cc
daemon/service-db-util.h
daemon/service-db.cc
daemon/service-db.hh
tests/daemon/unittest_service_db.cc
tests/meson.build

Add c-style DB interface and init/close DB when running daemon.

[ServiceDB] interface to handle DB data

---

daemon/main.c
packaging/machine-learning-agent.spec
tests/services/org.tizen.machinelearning.service.service.in

1. Add option to set DB path.
2. Enable tizen feature in spec.

[Build] enable tizen feature

---

daemon/mlops-agent-interface.c
meson.build
packaging/mlops-agent.spec
packaging/run-unittest.sh
tests/daemon/unittest_mlops_agent.cc

Code clean, update document and fix path to run unittest.

[CodeClean] fix path to run test

---

.github/workflows/tizen.gbs.conf
.github/workflows/tizen_gbs.yml

This patch adds a GitHub Actions workflow that runs GBS Tizen build and unit testing.
Signed-off-by: Wook Song <wook16.song@samsung.com>

GitHub/Actions: Add a workflow running gbs Tizen build

---

daemon/mlops-agent-interface.c

Fix invalid typecast to get the dbus proxy.

[CodeClean] invalid typecast

---

plugin-parser/mlops-plugin-parser.cc

- json file is updated from separated files to a single file.
- add parsing updated json format code in ``mlops-plugin-parser.cc``.
- an example of the json file is shown below. The name of the json file is ``rpk_config.json``.
```
{  
"models": [  
{  
"name": "image_classification",  
"model": "mobilenet_v2_1.0_224.tflite",  
"activate": true,
"description": "Image classification model for mobile devices (version 2.1.0)"  
},
{  
"name": "object_detection",  
"model": "ssd_mobilenet_v1_100_320_uint8_default_1.tflite",
"activate": true,  
"description": "Object detection model for system (version 1)"  
}  
],  
"pipelines": [
{  
"name": "pipeline1",  
"pipeline": "videotestsrc is-live=true ! videoconvert ! tensor_converter ! tensor_sink async=false"
},  
{  
"name": "pipeline2", …
```

[modified] modified mlops-plugin-parser for parsing updated json format.

---

tests/plugin-parser/unittest_mlops_plugin_parser.cc

Code clean, use glib function to remove temp file for unittest.

[CodeClean/Test] use glib function

---

daemon/mlops-agent-interface.c

- Replace the `path` from DB with resolved RPK resource path
REF: https://github.com/nnstreamer/api/pull/547

[agent] Let mlops-agent lib resolve RPK path

---

.github/workflows/publish_docs.yml

- Publish doxybook daily and upload it to artifact.
Result: https://github.com/gichan-jang/deviceMLOps.MLAgent/actions/runs/10556209213

[Action] Publish doxybook daily

---

meson.build

Code clean, check supported args and set warning flags.

[Meson] warning flags

---

daemon/log.h
daemon/mlops-agent-android.c
daemon/mlops-agent-interface.c
daemon/mlops-agent-internal.h
jni/mlops-agent.mk

Code clean, add internal header and cleanup script for android build.

[Android] internal header

---

daemon/mlops-agent-node.c

Fix svace issue, node id value with lock.

[CodeClean] fix svace issue

---

.github/workflows/mlops_agemt_testhub.yml

Upload coverage result to TestHub.

[Action] Add testhub action
